name: Build

on: [pull_request]

jobs:
  build-and-test:
    name: swift ${{ matrix.swift-version }} - '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["5.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v1.21.0
        with: 
          swift-version: ${{ matrix.swift-version }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build Package
        run: swift build --build-tests
      - name: Test Package
        run: swift test --parallel --enable-code-coverage
