name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release - Automatic Versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Generate Documentation
        run: |
          swift package --allow-writing-to-directory docs generate-documentation --target Either --disable-indexing --transform-for-static-hosting --hosting-base-path Either --output-path docs
      - name: Commit and Push
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add ./docs
          git commit -m "docs: generate docs [skip ci]"
          git push
      - name: Create New Version
        uses: TriPSs/conventional-changelog-action@v3.17.0
        id: changelog
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          git-message: 'release: {version}'
          git-user-name: ${{ secrets.USERNAME }}
          git-user-email: ${{ secrets.EMAIL }}
          tag-prefix: ''
          output-file: 'CHANGELOG.md'
          release-count: 0
          skip-version-file: 'true'
          skip-commit: 'false'
      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          tag: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ secrets.ACCESS_TOKEN }}
